services:
  postgres:
    container_name: nm_postgres
    image: 'postgres:14.2-alpine'
    environment:
      POSTGRES_PASSWORD: MARKOV
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local