server:
  address: 192.168.0.116
  error:
    include-stacktrace: always
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nm
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #      ddl-auto: update
      ddl-auto: create
    generate-ddl: true
    database: postgresql
    properties:
      hibernate:
        globally_quoted_identifiers: true